
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  lamba function to generate thumbnail from s3 bucket

Transform:
- AWS::Serverless-2016-10-31


Resources:
  generatethumbnail:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/index.generateThumbnail
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that returns a static string.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
    
    LambdaLayer:
      Type: AWS::Serverless::LayerVersion
      Properties:
        LayerName: ffmpeg 
        Description: FFMPEG for AWS Lambda
        ContentUri: build/layer
        CompatibleRuntimes:
          - nodejs10.x
          - python3.6
          - ruby2.5
          - java8
          - go1.x
        LicenseInfo: GPL-2.0-or-later
        RetentionPolicy: Retain

      Outputs:
        LayerVersion:
          Description: Layer ARN Reference
          Value: !Ref LambdaLayer

      Metadata:
        AWS::ServerlessRepo::Application:
          Name: ffmpeg-lambda-layer
          Description: >
            Static build of FFmpeg/FFprobe for Amazon Linux 2,
            packaged as a Lambda layer. Bundles FFmpeg 4.1.3
          Author: Gojko Adzic
          SpdxLicenseId: GPL-2.0-or-later
          LicenseUrl: LICENSE.txt
          ReadmeUrl: README-SAR.md 
          Labels: ['layer', 'lambda', 'ffmpeg', 'ffprobe']
          HomePageUrl: https://github.com/serverlesspub/ffmpeg-aws-lambda-layer
          SemanticVersion: 1.0.0
          SourceCodeUrl: https://github.com/serverlesspub/ffmpeg-aws-lambda-layer